### ISSUE TITLE
[TASK] change font weigth to scrapper.css

### ISSUE THREAD

**Issue by yamilt351** [yamilt351/scraper#79]
## Task Description

![image](https://github.com/yamilt351/scraper/assets/88646148/34d4c4d1-cfc9-4929-8f41-bafe6311204d)

make it bold
just add
```
font-weight:bold 
```
to it's css property

**Comment by 2div** [comment]
Hi , if no one working in this task , can you assigned to me?
This is will be my first contribution in github.

**Comment by yamilt351** [comment]
Hello and welcome!, done.

**Comment by 2div** [comment]
Thank you for this opportunity and i am very excited.

I just forked the repo to my GitHub and created a branch .

I want ask for clarification , you want me to make the font-bold for the input field of the "keyword to search" and the 
start scrapping button ? 

In  below screenshot , I made font-bold
![image](https://github.com/yamilt351/scraper/assets/96177680/f6794eab-8eaf-48d3-bd04-395bb6f0b90a)


Please correct me if am wrong because this my first time i contribute in GitHub ?

**Comment by yamilt351** [comment]
only for the start Scrapping button

**Comment by 2div** [comment]
Thank you for your clarification .
I want mention that the Scrapping button is in joined.css not in scrapper.css

**Comment by yamilt351** [comment]
thank you! sorry for that

**Comment by 2div** [comment]
I did push , but after i forget to add the .env file and i did not made npm run test 

I did cd to src folder and then i added .env file and then made npm i  , then when i did npm run dev . i got below message in screen shot :  

![image](https://github.com/yamilt351/scraper/assets/96177680/a90db96f-17f0-4c2f-833d-5d97561bb5bb)

i really do not understand the message. Please what to do or should not make npm run test ?

**Comment by yamilt351** [comment]
in your case is not necessary run tests , at least for this pr. This is necessary to check that your changes does not break the code, but you just change the font-weight. So is ok!

**Comment by yamilt351** [comment]
remember please create your commit with resolve #79 and your pr too, so github can handle the issue state automatically
